### ISSUE TITLE
Add `stock` keymap for Dilemma

### ISSUE THREAD

**Issue by 0xcharly** [Bastardkb/bastardkb-qmk#22]
Fork the `stock` keymap from the Charybdis 3x5:

- home row
- auto mouse layer
- all other goodies

**Comment by 0xcharly** [comment]
Default DPI: 1200
Snipping DPI: 400 (or whatever the default is currently)

Double check for jitter on snipping.

**Comment by freznel10** [comment]
Would like to suggest a lower default dpi of 800 to 1000 as it gives a more "pleasant experience". At 1200, you get the feeling that the trackpad moves too fast.

**Comment by 0xcharly** [comment]
I don't have a strong preference personally. In my testing, I noticed that 1000 seemed to provide a good balance between accuracy and speed for my use case, so we could settle on that for the default value?
