### ISSUE TITLE
Dilemma - middle click

### ISSUE THREAD

**Issue by bstiq** [Bastardkb/bastardkb-qmk#29]
At the moment the dilemma assembled vial doesn't have a middle click mapped.

My proposition: add it here
![image](https://user-images.githubusercontent.com/1847115/191046733-d6410bcb-7523-4337-b3d8-d31c3d355e72.png)

And remove the 2 reset keys / move them to another layer, as it's easy to trigger them by mistake

**Comment by 0xcharly** [comment]
Done.
