### ISSUE TITLE
Features missing on Charybdis Splinky Vial

### ISSUE THREAD

**Issue by bstiq** [Bastardkb/bastardkb-qmk#30]
File: bastardkb_charybdis_4x6_v2_splinky_vial.uf2 (from release section)

This image does not have the same features enabled as other keyboards (eg. Skeletyl). Check below for screenshost.
I did not check the other files.

![image](https://user-images.githubusercontent.com/1847115/199059534-dd732b06-cb56-47c6-a21b-834e039fb3c6.png)

![image](https://user-images.githubusercontent.com/1847115/199059554-e6f348c7-92b8-4f78-82f0-db029ea6e47b.png)

**Comment by alexeyatbluescape** [comment]
I've enabled some features myself here, and one extra layer, more macros: https://github.com/Bastardkb/bastardkb-qmk/compare/bkb-vial...choovick:bastardkb-qmk:bkb-vial-choovick-final

but I tried to enable https://github.com/qmk/qmk_firmware/blob/master/docs/one_shot_keys.md but without success so far...
