### ISSUE TITLE
`eeconfig_init_kb()` not called when `VIA_ENABLED=yes`

### ISSUE THREAD

**Issue by 0xcharly** [Bastardkb/bastardkb-qmk#35]
This is at least the case for the Dilemma integrated, with the `via` keymap.

Sending `EE_CLR` does not trigger a eeprom clear (as far as I can tell, the keyboard does not seem to even reset).

This however works as expected with the same keymap compiled with `-e VIA_ENABLE=no`.

**Comment by casuanoob** [comment]
This appears fixed sometime between now and when the issue was opened - `EE_CLR ` worked as expected for me when sending it on dilemma 3x5_3 with `VIA_ENABLED=yes`
