### ISSUE TITLE
Could not reflash scylla over usba hub

### ISSUE THREAD

**Issue by ahonnecke** [Bastardkb/bastardkb-qmk#43]
Mac OS, recent scylla (https://github.com/Bastardkb/bastardkb-qmk/releases/download/v3.2.0/bastardkb_scylla_v2_splinky_3_stock.uf2)

I had A USBC to USBA hub connected to the macbook, and then a USBA to USBC cable coming out of the hub.  When connected like this, double clicking the button on the button on the bottom did not result in the keyboard automounting storage (enabling reflash).  I had to change it to a USBC to USBC cable running directly from the machine to the keyboard to get it to work.

To be clear, this is solved for me, I'm just making the issue at Quentin's request.

**Comment by 0xcharly** [comment]
That's a common issue with some docks and sometimes even some cables. Not a firmware issue. Glad you got it sorted.
