### ISSUE TITLE
Skeletyl default firmware

### ISSUE THREAD

**Issue by bstiq** [Bastardkb/bastardkb-qmk#6]
Hi @0xcharly ,

When flashing skeletyls myself, I use miryoku.

I'd also like to include vial as default.

This means:
- including a `make bastardkb/skeletyl/v2/elitec:manna-harbour_miryoku` in your script that generates hex files
- somehow including vial with miryoku on the skeletyl

I'm a bit unsure on how to do the second one though, let me know if you have ideas.

Regards,

**Comment by 0xcharly** [comment]
Building the Skeletyl firmware with Miryoku and Via support is fairly trivial, but building with Vial support is not.

To build Miryoku for Skeletyl from `bkb-vial`, we need to

1. copy the Skeletyl's `vial.json` file under `layouts/community/split_3x5_3/manna-harbour_miryoku`:

    ```sh
    cp keyboards/bastardkb/skeletyl/keymaps/vial/vial.json layouts/community/split_3x5_3/manna-harbour_miryoku/.
    ```

2. generate and add a `VIAL_KEYBOARD_UID` to `users/manna-harbour_miryoku/config.h`:

    ```sh
    util/vial_generate_keyboard_uid.py >> users/manna-harbour_miryoku/config.h
    ```

3. comment out `AUTO_SHIFT_NO_SETUP` in `users/manna-harbour_miryoku/config.h` (already defined in Vial's master I believe):

    ```c
     // #define AUTO_SHIFT_NO_SETUP
    ```

And finally build the firmware with the following command-line:

```sh
qmk compile -j0 -kb bastardkb/skeletyl/v2/elitec -km manna-harbour_miryoku -e VIA_ENABLE=yes -e VIAL_ENABLE=yes -e VIAL_INSECURE=yes -e LTO_ENABLE=yes -e SPACE_CADET_ENABLE=no -e TAP_DANCE_ENABLE=no -e VIALRGB_ENABLE=yes
```

This just fits on AVR:

```
* The firmware size is approaching the maximum - 28644/28672 (99%, 28 bytes free)
```

I could stash the changes above in a separate branch based on `bkb-vial` and use that to generate the firmware.  I don't expect too many conflict with future updates to Miryoku.

**Comment by bstiq** [comment]
Hey,

If it's too much effort - don't bother.
Skeletyl firmware with miryoku and without vial is fine.

We can switch to miryoku+vial once we have more space (rp2040) and/or it generates less conflicts between the 2 of them and/or it's less effort, this seems like you're going too much out of your way.

**Comment by 0xcharly** [comment]
Done.  https://github.com/Bastardkb/bastardkb-qmk/releases/tag/v2.0.3 is the first release to contain those firmwares:

- `bastardkb_skeletyl_v1_elitec_miryoku.hex`
- `bastardkb_skeletyl_v1_elitec_miryoku-vial.hex`
- `bastardkb_skeletyl_v2_elitec_miryoku.hex`
- `bastardkb_skeletyl_v2_elitec_miryoku-vial.hex`
- `bastardkb_skeletyl_blackpill_miryoku.hex`
- `bastardkb_skeletyl_blackpill_miryoku-vial.hex`

I've left the default base layer unchanged, which is Colemak DH for Miryoku.  Let me know if you prefer another default layer (_eg._ QWERTY).

Closing this for now.
