### ISSUE TITLE
qmk-version

### ISSUE THREAD

**Issue by Eloy98** [Bastardkb/bastardkb-qmk#7]
hi，which version of qmk is bkb-stemcell using?

**Comment by 0xcharly** [comment]
`bkb-stemcell` is rebased on an slightly older version of `qmk:develop`.  The PR needs to be updated, as it does not build on the latest `qmk:develop` branch, but this is currently blocked on some QMK core work (namely, the convertor functions to and from pro-micro footprint).

I'll update the `bkb-stemcell` branch as soon as the PR is merged with `qmk:develop` (or even a before that when the PR is updated to build against the latest `qmk:develop`).
